//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicXCFMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int product_id { get; set; }
        public string contains_nuts_yn { get; set; }
        public decimal price { get; set; }
        public string ingredients { get; set; }
    
        public virtual Products Product { get; set; }
    }
}
