//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicXCFMS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogicXDBContext : DbContext
    {
        public LogicXDBContext()
            : base("name=LogicXDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer_Orders> Customer_Orders { get; set; }
        public virtual DbSet<Customer_Orders_Products> Customer_Orders_Products { get; set; }
        public virtual DbSet<Customer_Payment_Methods> Customer_Payment_Methods { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Drink> Drinks { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<In_Offers> In_Offers { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<Menus_Products> Menus_Products { get; set; }
        public virtual DbSet<Messages_Logs> Messages_Logs { get; set; }
        public virtual DbSet<Offers> Offers { get; set; }
        public virtual DbSet<Orders_has_Users> Orders_has_Users { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Ref_Drink_Size> Ref_Drink_Size { get; set; }
        public virtual DbSet<Ref_Logs_Types> Ref_Logs_Types { get; set; }
        public virtual DbSet<Ref_Order_Status_Code> Ref_Order_Status_Code { get; set; }
        public virtual DbSet<Ref_Payment_Methods> Ref_Payment_Methods { get; set; }
        public virtual DbSet<Ref_Product_Types> Ref_Product_Types { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
