//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicXCFMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roles
    {
        public int user_id { get; set; }
        public int role_id { get; set; }
        public Nullable<System.DateTime> role_assign_date { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Users User { get; set; }
    }
}
